//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiant.Custom.ProductsHistory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitTestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radiant.Custom.ProductsHistory.Resources.UnitTestsResources", typeof(UnitTestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;&lt;html lang=&quot;en-ca&quot; class=&quot;a-no-js&quot; data-19ax5a9jf=&quot;dingo&quot;&gt;&lt;!-- sp:feature:head-start --&gt;
        ///&lt;head&gt;&lt;script&gt;var aPageStart = (new Date()).getTime();&lt;/script&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///
        ///&lt;script type=&apos;text/javascript&apos;&gt;var ue_t0=ue_t0||+new Date();&lt;/script&gt;
        ///&lt;!-- sp:feature:cs-optimization --&gt;
        ///&lt;meta http-equiv=&apos;x-dns-prefetch-control&apos; content=&apos;on&apos;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://images-na.ssl-images-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://m.media-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns-pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amazon_Product1_SourceCode {
            get {
                return ResourceManager.GetString("Amazon_Product1_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;&lt;html lang=&quot;en-ca&quot; class=&quot;a-no-js&quot; data-19ax5a9jf=&quot;dingo&quot;&gt;&lt;!-- sp:feature:head-start --&gt;
        ///&lt;head&gt;&lt;script&gt;var aPageStart = (new Date()).getTime();&lt;/script&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///
        ///&lt;script type=&apos;text/javascript&apos;&gt;var ue_t0=ue_t0||+new Date();&lt;/script&gt;
        ///&lt;!-- sp:feature:cs-optimization --&gt;
        ///&lt;meta http-equiv=&apos;x-dns-prefetch-control&apos; content=&apos;on&apos;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://images-na.ssl-images-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://m.media-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns-pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amazon_Product2_SourceCode {
            get {
                return ResourceManager.GetString("Amazon_Product2_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang= &quot;en&quot; &gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title data-react-helmet=&quot;true&quot;&gt;PlayStation 5 DualSense Wireless Controller - White | Best Buy Canada&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta content=&apos;width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=no&apos; name=&apos;viewport&apos; /&gt;
        ///    &lt;meta name=&quot;theme-color&quot; content=&quot;#0046be&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;https://www.bestbuy.ca&quot; /&gt;
        ///    &lt;link rel=&quot;preconnect&quot; href=&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BestBuy_Product1_SourceCode {
            get {
                return ResourceManager.GetString("BestBuy_Product1_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en-ca&quot;&gt;&lt;head&gt;&lt;title&gt;DualShock 4 PS4 Controller Wireless for PlayStation 4 - Jet Black - Newegg.ca&lt;/title&gt;&lt;meta charSet=&quot;utf-8&quot;/&gt;&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;&lt;meta name=&quot;referrer&quot; content=&quot;always&quot;/&gt;&lt;meta name=&quot;keywords&quot; content=&quot;Newegg, Newegg.ca, DualShock 4 PS4 Controller Wireless for PlayStation 4 - Jet Black&quot;/&gt;&lt;meta name=&quot;description&quot; content=&quot;Buy DualShock 4 PS4 Controller Wireless for PlayStation 4 - Jet Black with fast shipping and top- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Newegg_Product1_SourceCode {
            get {
                return ResourceManager.GetString("Newegg_Product1_SourceCode", resourceCulture);
            }
        }
    }
}
