//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiantReader.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiantReader.Tests.Resources.ResourceDom", typeof(ResourceDom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///&lt;script src=&quot;https://js-agent.newrelic.com/nr-1216.min.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot;&gt;window.NREUM||(NREUM={});NREUM.info={&quot;beacon&quot;:&quot;bam-cell.nr-data.net&quot;,&quot;errorBeacon&quot;:&quot;bam-cell.nr-data.net&quot;,&quot;licenseKey&quot;:&quot;f2edcff25e&quot;,&quot;applicationID&quot;:&quot;190034&quot;,&quot;transactionName&quot;:&quot;dgwMEkpfWVsHERpFWUcIEUlRXlFSGg==&quot;,&quot;queueTime&quot;:0,&quot;applicationTime&quot;:168,&quot;agent&quot;:&quot;&quot;}&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;(wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArchiveOfOurOwn_2022_05_09 {
            get {
                return ResourceManager.GetString("ArchiveOfOurOwn_2022_05_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html class=&quot;wf-loading wf-verdana-n4-loading&quot;&gt;&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;ROBOTS&quot; content=&quot;NOARCHIVE&quot;&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///&lt;meta name=&quot;apple-itunes-app&quot; content=&quot;app-id=1192753879&quot;&gt;
        ///&lt;link href=&quot;//ff74.b-cdn.net&quot; rel=&quot;preconnect&quot;&gt;
        ///&lt;link href=&quot;//adservice.google.com&quot; rel=&quot;preconnect&quot;&gt;
        ///&lt;link href=&quot;//googleads.g.doubleclick.net&quot; rel=&quot;preconnect&quot;&gt;&lt;meta name=&quot;google-site-verification&quot; content=&quot;azVIufmnM7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fanfiction_2022_04_08 {
            get {
                return ResourceManager.GetString("Fanfiction_2022_04_08", resourceCulture);
            }
        }
    }
}
